### PR TITLE
Fixed Hassans ability check and added nod

### PR DESCRIPTION
**Pull request by griffin-urton**

### CODE REVIEW

**Review by nre226 — CHANGES_REQUESTED** [review]
Dig the changes. Please update the ReadME and add support for both nod and nods

**Comment by griffin-urton** [comment]
Changes made. Thanks for the speedy review

**Comment by nre226** [comment]
All looks good but on commit 222ce7962e991c445c9ecbe41766026c417aa779 I think prettier went nuts lol. I can keep it if it is a big headache to revert on your end but if you can prevent all those space changes that'd be dope. Thanks :)

**Review by nre226 — APPROVED** [review]
Awesome. Changes accepted. Let me know if need the bot to be moved over to the Island Chat or I can do it later tonight.

**Pull request merged**
